import {default as _FontAwesome} from 'react-native-vector-icons/FontAwesome';
import {default as _Entypo} from 'react-native-vector-icons/Entypo';
import {default as _Feather} from 'react-native-vector-icons/Feather';
import {default as _Foundation} from 'react-native-vector-icons/Foundation';
import {default as _Ionicons} from 'react-native-vector-icons/Ionicons';
import {default as _MaterialIcons} from 'react-native-vector-icons/MaterialIcons';
import {default as _MaterialCommunityIcons} from 'react-native-vector-icons/MaterialCommunityIcons';
import {default as _Octicons} from 'react-native-vector-icons/Octicons';
import {default as _Zocial} from 'react-native-vector-icons/Zocial';
import {default as _SimpleLineIcons} from 'react-native-vector-icons/SimpleLineIcons';
import {default as _EvilIcons} from 'react-native-vector-icons/EvilIcons';

export const FontAwesome = _FontAwesome;
export const Entypo = _Entypo;
export const Feather = _Feather;
export const Foundation = _Foundation;
export const Ionicons = _Ionicons;
export const MaterialIcons = _MaterialIcons;
export const MaterialCommunityIcons = _MaterialCommunityIcons;
export const Octicons = _Octicons;
export const Zocial = _Zocial;
export const SimpleLineIcons = _SimpleLineIcons;
export const EvilIcons = _EvilIcons;
